language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
#install:
  # install php packages required for running a web server from drush on php 5.3
  # - sudo apt-get install -y --force-yes php5-cgi php5-mysql
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
